[versions]
agp = "8.13.1"
kotlin = "2.2.21"
protobufVersion = "4.33.1"

[libraries]
junit = { module = "junit:junit", version = "4.13.2" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.7.0" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.7.0" }
androidx-test-ext = { module = "androidx.test.ext:junit", version = "1.3.0" }
androidx-annotations = { module = "androidx.annotation:annotation", version = "1.9.1" }
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.9.0" }
protoc-core = { module = "com.google.protobuf:protoc", version = "4.33.1" }
protoc-kotlin = { module = "com.google.protobuf:protoc-gen-kotlin", version = "1.28.0" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin", version.ref = "protobufVersion" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
protobuf-compiler = { id = "com.google.protobuf", version = "0.9.5" }